apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: system
  labels:
    control-plane: webhook
spec:
  selector:
    matchLabels:
      control-plane: webhook
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: webhook
        name: webhook
    spec:
      securityContext:
      containers:
      - command:
        - /webhook
        image: webhook:latest
        imagePullPolicy: Always
        name: webhook
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: opendatahub-operator-controller-webhook-cert
      terminationGracePeriodSeconds: 10
